language: python
python:
  - "2.7"

# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install gfortran-4.9
  - sudo ln -fs /usr/bin/gfortran-4.9 /usr/bin/gfortran && gfortran --version
  - export PATH=".:$PATH"

before_script:
  - gfortran test.f90 -o test

script: nosetests
