language: python
python:
  - "2.7"

sudo: false

addons:
  apt:
    sources:
      - kalakris-cmake
      - ubuntu-toolchain-r-test
    packages:
      - gfortran-4.9
      - binutils
      - cmake

# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests

before_install:
  - export PATH=".:$PATH"

#install:
#  - ln -fs /usr/bin/gfortran-4.9 "$HOME/.local/bin/gfortran" && gfortran --version
#  - ls -l /usr/bin/gfortran-4.9

before_script:
  - ls -l /usr/bin/gfortran-4.9
  - /usr/bin/gfortran-4.9 --version
  - /usr/bin/gfortran-4.9 test.f90 -o test

script: nosetests
