language: python
python:
  - "2.7"

sudo: false

addons:
  apt:
    packages:
    - gfortran-4.9

# command to install dependencies
# install: "pip install -r requirements.txt"
# command to run tests

before_install:
  - export PATH=".:$PATH"

before_script:
  - cd /usr/bin
  - ls -al
  - gcc --version
  - gfortran --version
  - /usr/bin/gfortran test.f90 -o test

script: nosetests
